version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c 'max_connections=100'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/blogdb"
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      JWT_SECRET: your-256-bit-secret
      DOCKER_ENV: "true"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local